# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Github Style"
description = "github hugo theme"
homepage = "https://github.com/todevops"
tags = ["blog", "google analytics"]
features = ["google analytics"]

[author]
  name = "JeremyTowne"
  homepage = "https://github.com/todevops"
